# Generated by Django 4.2.4 on 2023-08-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_women_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
